#!/usr/bin/env bash
#
# Interactive setup script for swe-opd-remote-docker.
# Generates all four *.local.env files from user input.
#
# Usage:
#   bash scripts/setup.sh              # interactive prompts
#   bash scripts/setup.sh --check      # validate existing config without changes
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_DIR="${PROJECT_ROOT}/config/bootstrap"

# ── Helpers ──────────────────────────────────────────────────────────

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

info()  { printf "${GREEN}[OK]${NC}   %s\n" "$*"; }
warn()  { printf "${YELLOW}[WARN]${NC} %s\n" "$*"; }
err()   { printf "${RED}[ERR]${NC}  %s\n" "$*"; }
header(){ printf "\n${BOLD}── %s ──${NC}\n\n" "$*"; }

# Prompt with default value.  Usage: ask VAR "prompt text" "default"
ask() {
    local var_name="$1" prompt="$2" default="${3:-}"
    if [[ -n "${default}" ]]; then
        printf "  %s [%s]: " "${prompt}" "${default}"
    else
        printf "  %s: " "${prompt}"
    fi
    read -r value
    value="${value:-${default}}"
    eval "${var_name}=\"\${value}\""
}

# Ask yes/no.  Usage: ask_yn VAR "prompt" "y"
ask_yn() {
    local var_name="$1" prompt="$2" default="${3:-y}"
    local hint
    if [[ "${default}" == "y" ]]; then hint="Y/n"; else hint="y/N"; fi
    printf "  %s [%s]: " "${prompt}" "${hint}"
    read -r value
    value="${value:-${default}}"
    case "${value}" in
        [yY]*) eval "${var_name}=true" ;;
        *)     eval "${var_name}=false" ;;
    esac
}

write_env() {
    local file="$1"
    shift
    mkdir -p "$(dirname "${file}")"
    printf '' > "${file}"
    for line in "$@"; do
        printf '%s\n' "${line}" >> "${file}"
    done
    info "Wrote ${file}"
}

# ── Check mode ───────────────────────────────────────────────────────

if [[ "${1:-}" == "--check" ]]; then
    header "Checking existing configuration"
    ok=true
    for role in model_serving agent_rollout rollout_service remote_rollout_client; do
        f="${CONFIG_DIR}/${role}.local.env"
        if [[ -f "${f}" ]]; then
            info "${role}.local.env exists"
        else
            warn "${role}.local.env missing — run 'bash scripts/setup.sh' to create"
            ok=false
        fi
    done
    if ${ok}; then
        info "All config files present."
    fi
    exit 0
fi

# ── Interactive setup ────────────────────────────────────────────────

printf "\n${BOLD}swe-opd-remote-docker — Interactive Setup${NC}\n"
printf "This will create the four .local.env files under config/bootstrap/.\n"
printf "Press Enter to accept defaults shown in [brackets].\n"

# ── 1. Gather common info ───────────────────────────────────────────

header "General info"

ask SSH_USER     "Your username on Server B (taurus)" ""
ask SSH_HOST     "Server B hostname"                   "taurus.cs.ucsb.edu"
ask SSH_KEY      "Path to your SSH private key for Server B" ""

if [[ ! -f "${SSH_KEY}" ]]; then
    warn "SSH key not found at ${SSH_KEY} — make sure it exists before running."
fi

ask MODEL_PATH   "HuggingFace model name or local path for student model" "Kwai-Klear/Klear-AgentForge-8B"
ask MODEL_NAME   "Served model name (used in API calls)"                  "${MODEL_PATH}"

# ── 2. Server A: Model serving ──────────────────────────────────────

header "Server A — SGLang model serving"

ask SGLANG_PYTHON  "Python binary with sglang installed" "python3"
ask SGLANG_MODE    "Launch mode (single / router)"       "single"
ask SGLANG_HOST    "SGLang bind host"                    "127.0.0.1"
ask SGLANG_PORT    "SGLang bind port"                    "30000"
ask SGLANG_TP      "Tensor parallelism (GPUs per worker)" "1"
SGLANG_DP="1"
if [[ "${SGLANG_MODE}" == "router" ]]; then
    ask SGLANG_DP  "Data parallelism (number of workers)" "2"
fi
ask SGLANG_MEM     "GPU memory fraction"                 "0.80"
ask SGLANG_EXTRA   "Extra SGLang args (e.g. --trust-remote-code)" "--trust-remote-code"

ask TUNNEL_REMOTE_PORT "Remote port on Server B for model reverse tunnel" "32000"

write_env "${CONFIG_DIR}/model_serving.local.env" \
    "# Auto-generated by scripts/setup.sh" \
    "SGLANG_PYTHON_BIN=${SGLANG_PYTHON}" \
    "SGLANG_MODEL_PATH=${MODEL_PATH}" \
    "SGLANG_LAUNCH_MODE=${SGLANG_MODE}" \
    "SGLANG_HOST=${SGLANG_HOST}" \
    "SGLANG_PORT=${SGLANG_PORT}" \
    "SGLANG_TP=${SGLANG_TP}" \
    "SGLANG_DP_SIZE=${SGLANG_DP}" \
    "SGLANG_MEM_FRACTION_STATIC=${SGLANG_MEM}" \
    "SGLANG_EXTRA_ARGS=${SGLANG_EXTRA}" \
    "SGLANG_API_KEY=EMPTY" \
    "SGLANG_MODEL_NAME=${MODEL_NAME}" \
    "SGLANG_SMOKE_PROMPT=Reply with exactly: bootstrap-ok" \
    "" \
    "# Reverse tunnel: expose SGLang to Server B" \
    "SGLANG_TUNNEL_SSH_USER=${SSH_USER}" \
    "SGLANG_TUNNEL_SSH_HOST=${SSH_HOST}" \
    "SGLANG_TUNNEL_SSH_KEY=${SSH_KEY}" \
    "SGLANG_TUNNEL_REMOTE_HOST=127.0.0.1" \
    "SGLANG_TUNNEL_REMOTE_PORT=${TUNNEL_REMOTE_PORT}"

# ── 3. Server B: Agent rollout ──────────────────────────────────────

header "Server B — Agent rollout"

ask MINI_PYTHON      "Python binary on Server B (with mini-swe-agent-plus deps)" "python3"
ask MINI_ROOT        "Path to mini-swe-agent-plus repo on Server B"              ""
ask_yn USE_CUSTOM_CFG "Use a custom base config YAML?" "n"
MINI_BASE_CFG_LINE=""
if [[ "${USE_CUSTOM_CFG}" == "true" ]]; then
    ask MINI_BASE_CFG "Path to custom base config on Server B" ""
    MINI_BASE_CFG_LINE="MINI_BASE_CONFIG=${MINI_BASE_CFG}"
fi

ask SWE_WORKERS      "Parallel rollout workers"              "2"
ask SWE_DOCKER_CONC  "Docker start concurrency"              "1"

write_env "${CONFIG_DIR}/agent_rollout.local.env" \
    "# Auto-generated by scripts/setup.sh" \
    "BOOTSTRAP_PYTHON_BIN=${MINI_PYTHON}" \
    "MINI_PYTHON_BIN=${MINI_PYTHON}" \
    "MINI_SWE_AGENT_PLUS_ROOT=${MINI_ROOT}" \
    "" \
    "# Remote SGLang endpoint (accessed via reverse tunnel from Server A)" \
    "REMOTE_API_BASE=http://127.0.0.1:${TUNNEL_REMOTE_PORT}" \
    "REMOTE_API_KEY=EMPTY" \
    "REMOTE_MODEL_NAME=${MODEL_NAME}" \
    "REMOTE_PROVIDER=openai" \
    "REMOTE_TEMPERATURE=0.0" \
    "REMOTE_DROP_PARAMS=true" \
    "" \
    "${MINI_BASE_CFG_LINE}" \
    "REMOTE_SMOKE_PROMPT=Reply with exactly: bootstrap-ok" \
    "" \
    "# SWE-bench settings" \
    "SWEBENCH_SUBSET=verified" \
    "SWEBENCH_SPLIT=test" \
    "SWEBENCH_WORKERS=${SWE_WORKERS}" \
    "SWEBENCH_DOCKER_START_CONCURRENCY=${SWE_DOCKER_CONC}" \
    "" \
    "# Workaround for LiteLLM cost-tracking errors" \
    "MSWEA_COST_TRACKING=ignore_errors"

# ── 4. Server B: Rollout service ────────────────────────────────────

header "Server B — Rollout HTTP service"

ask SVC_HOST     "Service bind host"         "0.0.0.0"
ask SVC_PORT     "Service bind port"         "18080"
ask SVC_WORKERS  "Max concurrent jobs"       "2"
ask SVC_TOKEN    "API bearer token (leave empty for no auth)" ""

SVC_TOKEN_LINE=""
if [[ -n "${SVC_TOKEN}" ]]; then
    SVC_TOKEN_LINE="ROLLOUT_SERVICE_API_TOKEN=${SVC_TOKEN}"
fi

write_env "${CONFIG_DIR}/rollout_service.local.env" \
    "# Auto-generated by scripts/setup.sh" \
    "BOOTSTRAP_PYTHON_BIN=${MINI_PYTHON}" \
    "ROLLOUT_SERVICE_HOST=${SVC_HOST}" \
    "ROLLOUT_SERVICE_PORT=${SVC_PORT}" \
    "ROLLOUT_SERVICE_MAX_WORKERS=${SVC_WORKERS}" \
    "${SVC_TOKEN_LINE}"

# ── 5. Server A: Remote rollout client ──────────────────────────────

header "Server A — Remote rollout client"

ask CLIENT_PYTHON  "Python binary on Server A (with PyYAML, openai, litellm)" "python3"

CLIENT_TOKEN_LINE=""
if [[ -n "${SVC_TOKEN}" ]]; then
    CLIENT_TOKEN_LINE="REMOTE_ROLLOUT_API_TOKEN=${SVC_TOKEN}"
fi

write_env "${CONFIG_DIR}/remote_rollout_client.local.env" \
    "# Auto-generated by scripts/setup.sh" \
    "BOOTSTRAP_PYTHON_BIN=${CLIENT_PYTHON}" \
    "REMOTE_ROLLOUT_SERVICE_BASE=http://127.0.0.1:${SVC_PORT}" \
    "${CLIENT_TOKEN_LINE}" \
    "" \
    "# SSH tunnel to Server B rollout service" \
    "REMOTE_ROLLOUT_USE_SSH_TUNNEL=true" \
    "REMOTE_ROLLOUT_SSH_USER=${SSH_USER}" \
    "REMOTE_ROLLOUT_SSH_HOST=${SSH_HOST}" \
    "REMOTE_ROLLOUT_SSH_KEY=${SSH_KEY}" \
    "REMOTE_ROLLOUT_LOCAL_PORT=${SVC_PORT}" \
    "REMOTE_ROLLOUT_REMOTE_HOST=127.0.0.1" \
    "REMOTE_ROLLOUT_REMOTE_PORT=${SVC_PORT}" \
    "" \
    "# For reset script: the reverse tunnel port used by the model" \
    "REMOTE_MODEL_TUNNEL_REMOTE_PORT=${TUNNEL_REMOTE_PORT}" \
    "" \
    "REMOTE_ROLLOUT_WAIT_TIMEOUT=0"

# ── Done ─────────────────────────────────────────────────────────────

header "Setup complete"
info "Config files written to ${CONFIG_DIR}/"
printf "\n"
printf "Next steps:\n"
printf "  1. Review the generated files and tweak values if needed.\n"
printf "  2. Copy the Server B configs to Server B:\n"
printf "       scp -i %s config/bootstrap/{agent_rollout,rollout_service}.local.env \\\\\n" "${SSH_KEY}"
printf "         %s@%s:<swe-opd-path>/config/bootstrap/\n" "${SSH_USER}" "${SSH_HOST}"
printf "  3. Run 'bash scripts/verify.sh' to test the full pipeline.\n"
printf "\n"
